
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number
        required: true
        type: string

jobs:
  auto-publish:
    name: "AutoPublish"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - run: yarn install --frozen-lockfile

      - run: yarn version --new-version ${{ github.event.inputs.version }} --no-commit-hooks --no-git-tag-version
        working-directory: packages/excalidraw

      - run: yarn build:esm
        working-directory: packages/excalidraw

      - run: yarn pack
        working-directory: packages/excalidraw

      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403  # v5
        with:
          commit_message: Bump version to ${{ github.event.inputs.version }}
          file_pattern: packages/excalidraw/package.json

      - name: GitHub Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65  # v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          generate_release_notes: true
          make_latest: true
          files: packages/excalidraw/*.tgz
